# Generated by Django 3.0.8 on 2020-07-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_payment_test_testrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='expert',
        ),
        migrations.AddField(
            model_name='appointment',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Expert'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TestRequest'),
        ),
        migrations.AddField(
            model_name='payment',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_request', to='app.Patient'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Laboratory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_successful',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='payment_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_request', to='app.Payment'),
        ),
    ]
