from .laboratory import Laboratory
from .lab_test import LabTest
from .expert import Expert
from .patient import Patient
from .time_slot import TimeSlot
from .test_description import TestDescription
from .appointment import Appointment
from .address import Address
from .payment import Payment